<a href="https://colab.research.google.com/github/Stp155906/Data-Science-For-Beginners/blob/main/Working_GradioInput.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Using Gradio to create a simple interface.

Check out the library on [github](https://github.com/gradio-app/gradio-UI) and see the [getting started](https://gradio.app/getting_started.html) page for more demos.

We'll start with a basic function that greets an input name.

In [ ]:
def greet(name):
  return "Hello " + name + "!"

greet("World")

Now we'll wrap this function with a Gradio interface.

In [2]:
!pip install -q gradio

     |████████████████████████████████| 5.1 MB 13.0 MB/s
     |████████████████████████████████| 84 kB 3.4 MB/s
     |████████████████████████████████| 1.1 MB 44.7 MB/s
     |████████████████████████████████| 272 kB 49.4 MB/s
     |████████████████████████████████| 54 kB 2.8 MB/s
     |████████████████████████████████| 140 kB 56.7 MB/s
     |████████████████████████████████| 212 kB 47.2 MB/s
     |████████████████████████████████| 2.3 MB 46.9 MB/s
     |████████████████████████████████| 57 kB 5.2 MB/s
     |████████████████████████████████| 84 kB 3.7 MB/s
     |████████████████████████████████| 271 kB 51.0 MB/s
     |████████████████████████████████| 94 kB 3.5 MB/s
     |████████████████████████████████| 144 kB 41.7 MB/s
     |████████████████████████████████| 63 kB 1.7 MB/s
     |████████████████████████████████| 80 kB 7.2 MB/s
     |████████████████████████████████| 68 kB 3.3 MB/s
     |████████████████████████████████| 54 kB 3.4 MB/s
     |████████████████████████████████| 43 kB 1.9 MB/s
     |████████████████████████████████| 856 kB 58.0 MB/s
     |████████████████████████████████| 4.0 MB 73.2 MB/s
     |████████████████████████████████| 62 kB 1.0 MB/s
  Building wheel for ffmpy (setup.py) ... done
  Building wheel for python-multipart (setup.py) ... done

In [3]:
import gradio

gradio.Interface(greet, "text", "text").launch(share=True)

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://10487.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)

(<gradio.routes.App at 0x7fdf555fc690>,
 'http://127.0.0.1:7860/',
 'https://10487.gradio.app')

In [4]:
from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)



#Downloading data from a sheet into Python as a Pandas DataFrame


---


Read back the random data that we inserted above and convert the result into a Pandas DataFrame.
[6]
124567839
worksheet = gc.open('Conscientious Choice').sheet1# get_all_values gives a list of rows.rows = worksheet.get_all_values()print(rows)import pandas as pdpd.DataFrame.from_records(rows)

---

In [5]:
worksheet = gc.open('Conscientious Choice').sheet1

#get_all_values gives a list of rows.
rows = worksheet.get_all_values()
print(rows)

import pandas as pd
list_all = pd.DataFrame.from_records(rows)
list_all

[['Category', 'Parent Company', 'Company', 'Score', '% Dem', 'Anti-Abortion candidate?', 'Metric Abortion', 'Pro-gun candidate?', 'Metric Gun', 'Pro-oil candidate?', 'Metric Oil', 'Anti-LGBTQ candidate?', 'Metric LGBTQ', 'Utilizes prison labor?', 'Environmental  Sourcing', 'Labor Sourcing', 'Historical  Allegations', '% of Discriminatory Cases per year'], ['Airline', '', 'Frontier', '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Airline', '', 'Alaska Airlines', '44', '54', '', '', 'Yes', '10', '', '', '', '', '', '', '', '', ''], ['Airline', '', 'United Airlines', '42', '72', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Airline', '', 'Allegiant', '38', '38', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Airline', '', 'Southwest', '36', '36', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Airline', '', 'Delta', '34', '54', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', '', '', ''], ['Airline', '', 'JetBlue', '53', '53', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Airline', '', 'American Airlines', '15', '45', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'Progressive', '60', '80', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'GEICO', '51', '61', '', '', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'Nationwide', '27', '47', 'Yes', '10', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'Farmers', '21', '31', '', '', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'Liberty Mutual', '14', '44', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'State Farm', '10', '40', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Insurance', '', 'Allstate', '6', '36', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Auto Parts', '', 'Advance Auto Parts', '68', '68', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Auto Parts', '', 'NAPA', '45', '45', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Auto Parts', '', 'AutoZone', '-2', '18', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', '', '', ''], ['Auto Parts', '', "O'Reilly Auto Parts", '-5', '25', 'Yes', '10', 'Yes', '10', 'Yes', '10', 'Yes', '', '', '', '', '', ''], ['Baby', 'P&G', 'Luvs', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Baby', 'P&G', 'Pampers', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Bank', '', 'Citibank', '50', '50', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Bank', '', 'Citizens Financial', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Bank', '', 'Chase', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Bank', '', 'Capital One', '25', '45', '', '', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Bank', '', 'Ally', '25', '25', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Bank', '', 'Wells Fargo', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', 'Yes', '', '', '', '', '', ''], ['Bank', '', 'Bank of America', '16', '46', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Bank', '', 'SunTrust', '14', '14', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Bank', '', 'PNC', '4', '24', '', '', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Candy', '', 'Godiva', '95', '95', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Lindt', 'Ghirardelli', '89', '89', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Lindt', 'Lindt', '89', '89', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Lindt', 'Russel Stover', '89', '89', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', '3 Muskateers', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Dove', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Life Savers', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'M&Ms', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Mars', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Milky Way', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Skittles', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Snickers', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Starburst', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mars', 'Twix', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'KitKat', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Nestle', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Almond Joy', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', 'Mondelez', 'Cadbury Creme Egg', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Heath Bar', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Hershey', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Jolly Rancher', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Milk Duds', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Mr. Goodbar', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', "Reece's", '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Rolo', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Twizzler', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Whoppers', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'York Peppermint Patty', '52', '52', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Sour Patch Kids', '51', '51', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Candy', '', 'Mondelez', '41', '51', 'Yes', '10', '', '', 'Yes', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Avis', '36', '36', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Budget ', '36', '36', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Zipcar', '36', '36', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Dollar', '31', '31', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Hertz', '31', '31', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Thrifty', '31', '31', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Alamo', '25', '25', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'Enterprise', '25', '25', '', '', '', '', 'Yes', '', '', '', '', '', '', '', ''], ['Car Rental', '', 'National', '25', '25', '', '', '', '', 'Yes', '', '', '', '', '', '', '', ''], ['Cellular', '', 'Google', '76', '86', 'Yes', '10', '', '', 'Yes', '', '', '', '', '', '', '', ''], ['Cellular', '', 'Sprint', '56', '66', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Cellular', '', 'T-Mobile', '43', '53', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Cellular', '', 'Verizon', '33', '53', 'Yes', '10', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Cellular', '', 'AT&T', '22', '42', 'Yes', '10', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'Unilever', 'Seventh Generation', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cleaning Supplies', '', 'Ajax', '72', '72', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cleaning Supplies', '', 'Fabuloso', '72', '72', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cleaning Supplies', '', 'Palmolive', '72', '72', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cleaning Supplies', '', 'Pinesol', '72', '72', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cleaning Supplies', '', 'Softsoap', '72', '72', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'P&G', 'Cascade', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'P&G', 'Dawn', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'P&G', 'Febreze', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'P&G', 'Microban', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'P&G', 'Mr. Clean', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Cleaning Supplies', 'P&G', 'Swiffer', '29', '59', 'Yes', '10', 'Yes', '10', 'Yes', '10', '', '', '', '', '', '', ''], ['Clothing', '', 'American Eagle', '100', '100', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Calvin Klein', '100', '100', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Tommy Hilfiger', '100', '100', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Kate Spade', '94', '94', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', "Levi's", '93', '93', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Coach', '89', '89', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Michael Kors', '89', '89', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Supreme', '82', '82', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Nordstrom', '81', '91', '', '', 'Yes', '10', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Banana Republic', '64', '74', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'GAP', '64', '74', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Old Navy', '64', '74', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'Lululemon', '62', '62', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', 'ModCloth', '46', '46', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Clothing', '', "Victoria's Secret", '16', '16', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'ELF', '100', '100', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Tom Ford', '100', '100', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Ulta', '99', '99', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Sephora', '85', '85', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Essie', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Giorgio Armani Beauty', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'IT Cosmetics', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', "L'Oreal", '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Lancome', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Maybelline', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'NYX', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Urban Decay', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Yves Saint Laurent', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Aveda', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Bobbi Brown', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Clinique', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Estee Lauder', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'MAC', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Smashbox', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Too Faced', '67', '67', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Cosmetics', '', 'Revlon', '3', '13', '', '', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Craft', '', 'Joann Fabrics', '9', '9', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Craft', '', 'Michaels', '97', '97', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Dairy', '', 'Fairlife', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Liquid IV', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', 'Unilever', 'Lipton', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Nescafe', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Nespresso', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Nesquik', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Nestea', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Perrier', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'S. Pellegrinio', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Aquafina', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Gatorade', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Naked', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Tropicana', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'BodyArmor', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Costa Coffee', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Dasani', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Gold Peak Tea', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Minute Maid', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Peace Tea', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Powerade', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Schweppes', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Simply', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Smart Water', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Topo-Chico', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Vitamin Water', '37', '47', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Drinks', '', 'Swiss Miss', '34', '34', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Apple', '95', '95', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Samsung', '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Sony', '78', '88', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Google', '76', '86', 'Yes', '10', '', '', 'Yes', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Dell', '62', '62', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Microsoft', '55', '75', 'Yes', '10', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Electronics', '', 'HP', '51', '61', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Electronics', '', 'Intel', '50', '60', '', '', '', '', 'Yes', '10', '', '', '', '', '', '', ''], ['Electronics', '', 'Best Buy', '43', '53', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', "Ben & Jerry's", '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', "Snyeder's-Lance", 'Archway Cookies', '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', "Snyeder's-Lance", 'Cape Cod Potato Chips', '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', "Snyeder's-Lance", 'Kettle Foods', '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', "Snyeder's-Lance", "Snyder's of Haver", '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', "Snyeder's-Lance", "Snyder's-Lance", '81', '81', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Mars', 'Combos', '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Mars', "Uncle Ben's", '76', '76', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Breyers', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Fudgsicle', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Good Humor', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', "Hellmann's", '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Klondike', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Knorr', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Magnum Ice Cream', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Popsicle', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', "Sir Kensington's", '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', 'Talenti', '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', 'Unilever', "Wall's Ice Cream", '92', '92', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Carnation', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Cheerios', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Coffee Mate', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'DiGior', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', "Dreyer's", '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Gerber', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Haagen-Dazs', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Hot Pockets', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Lean Cuisine', '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', "Stouffer's", '63', '63', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', "Cap'n Crunch", '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Cheetos', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Doritos', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Lays', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Life Cereal', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Pearl Milling Co', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Quaker', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Rice a Roni', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Ruffles', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Sabra', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '', ''], ['Food', '', 'Santitas', '53', '63', 'Yes', '10', '', '', '', '', '', '', '', '', '', '

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Category,Parent Company,Company,Score,% Dem,Anti-Abortion candidate?,Metric Abortion,Pro-gun candidate?,Metric Gun,Pro-oil candidate?,Metric Oil,Anti-LGBTQ candidate?,Metric LGBTQ,Utilizes prison labor?,Environmental Sourcing,Labor Sourcing,Historical Allegations,% of Discriminatory Cases per year
1,Airline,,Frontier,81,81,,,,,,,,,,,,,
2,Airline,,Alaska Airlines,44,54,,,Yes,10,,,,,,,,,
3,Airline,,United Airlines,42,72,Yes,10,Yes,10,Yes,10,,,,,,,
4,Airline,,Allegiant,38,38,,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,,,,0,,,,,,,,,,,,,,
592,,,,0,,,,,,,,,,,,,,
593,,,,0,,,,,,,,,,,,,,
594,,,,0,,,,,,,,,,,,,,
595,,,,0,,,,,,,,,,,,,,

In [ ]:
# Renaming Columns
list_all.columns = [
                    'Category', 
                    'Parent Company', 
                    'Company', 
                    'Score', 
                    '% Dem', 
                    'Anti-Abortion candidate?', 
                    'Metric Abortion' ,
                    'Pro-gun candidate?',
                    'Metric Gun', 
                    'Pro-oil candidate?',
                    'Metric Oil', 
                    'Anti-LGBTQ candidate?',
                    'Metric LGBTQ',
                    'Utilizes prison labor?',
                    'Environmental Sourcing ', 
                    'Labor Sourcing', 
                    'Historical Allegations ',
                    '% of Discriminatory Cases per year']
list_all
#list_all = list_all.columns['Category', 'Parent Company', 'Company', '% Dem', 'Anti-Abortion candidate?',  'Pro-gun candidate?',  'Pro-oil candidate?',  'Anti-LGBTQ candidate?',  'Utilizes prison labor?', 'Labor Sourcing ', 'Environmental Sourcing ',  'Historical Allegations ', '% Discriminatory Cases PY']
# the list underneith each category
list_all
# Dropping. duplicate. labels row
data = list_all.drop(labels=0, axis=0)
data

>



---



---



---

# Installing Dash


---



---



---



---

# Tesing Pycarat

In [ ]:
# install slim version (default)
!pip install pycaret

In [8]:
# Saving Dataframe to CSV 

data.to_csv('data.csv')

In [9]:
# load the iris dataset from pycaret repo
from pycaret.datasets import get_data
data = get_data('data')

,Unnamed: 0,Category,Parent Company,Company,Score,% Dem,Anti-Abortion candidate?,Metric Abortion,Pro-gun candidate?,Metric Gun,Pro-oil candidate?,Metric Oil,Anti-LGBTQ candidate?,Metric LGBTQ,Utilizes prison labor?,Environmental Sourcing,Labor Sourcing,Historical Allegations,% of Discriminatory Cases per year
0,1,Airline,NaN,Frontier,81,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Airline,NaN,Alaska Airlines,44,54.0,NaN,NaN,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Airline,NaN,United Airlines,42,72.0,Yes,10.0,Yes,10.0,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Airline,NaN,Allegiant,38,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Airline,NaN,Southwest,36,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Initialize Setup

In [ ]:
# initialize setup
#from pycaret.classification import *
#s = setup(data, target = 'Category', session_id = 123)

# 👉 Compare Models


---


This is the first step we recommend in the workflow of any supervised experiment in PyCaret. This function trains all the available models in the model library using default hyperparameters and evaluates performance metrics using cross-validation.




---

The output of this function is a table showing the mean cross-validated scores for all the models. The number of folds can be defined using the foldparameter (default = 10 folds). The table is sorted (highest to lowest) by the metric of choice which can be defined using the sortparameter (default = ‘Accuracy’)

In [ ]:

#best = compare_models(n_select = 15)
#compare_model_results = pull()

# 👽 Here is where I worked with the data



---



---



---

In [10]:
# ONLY need to uncomment this with new datasets
clean_data = data.drop(columns=data.columns[0])
clean_data

,Category,Parent Company,Company,Score,% Dem,Anti-Abortion candidate?,Metric Abortion,Pro-gun candidate?,Metric Gun,Pro-oil candidate?,Metric Oil,Anti-LGBTQ candidate?,Metric LGBTQ,Utilizes prison labor?,Environmental Sourcing,Labor Sourcing,Historical Allegations,% of Discriminatory Cases per year
0,Airline,NaN,Frontier,81,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Airline,NaN,Alaska Airlines,44,54.0,NaN,NaN,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Airline,NaN,United Airlines,42,72.0,Yes,10.0,Yes,10.0,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Airline,NaN,Allegiant,38,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Airline,NaN,Southwest,36,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
data
# The lower the number the least supportive vs higher the number being most supportive

,Unnamed: 0,Category,Parent Company,Company,Score,% Dem,Anti-Abortion candidate?,Metric Abortion,Pro-gun candidate?,Metric Gun,Pro-oil candidate?,Metric Oil,Anti-LGBTQ candidate?,Metric LGBTQ,Utilizes prison labor?,Environmental Sourcing,Labor Sourcing,Historical Allegations,% of Discriminatory Cases per year
0,1,Airline,NaN,Frontier,81,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Airline,NaN,Alaska Airlines,44,54.0,NaN,NaN,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Airline,NaN,United Airlines,42,72.0,Yes,10.0,Yes,10.0,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Airline,NaN,Allegiant,38,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Airline,NaN,Southwest,36,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,591,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,592,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,593,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,594,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,595,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN




---



# Part I — Creating an internal function Displaying UI

In [11]:
data_clean = pd.DataFrame(clean_data)
data_clean

clean_data = data_clean.to_csv('clean_data.csv')

In [12]:
import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [20]:
current_dir = os.path.dirname(os.path.realpath( '/content/clean_data.csv'))
data = pd.read_csv(os.path.join(current_dir, "/content/clean_data.csv"))

In [14]:
data.drop(columns=data.columns[0])

,Category,Parent Company,Company,Score,% Dem,Anti-Abortion candidate?,Metric Abortion,Pro-gun candidate?,Metric Gun,Pro-oil candidate?,Metric Oil,Anti-LGBTQ candidate?,Metric LGBTQ,Utilizes prison labor?,Environmental Sourcing,Labor Sourcing,Historical Allegations,% of Discriminatory Cases per year
0,Airline,NaN,Frontier,81,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Airline,NaN,Alaska Airlines,44,54.0,NaN,NaN,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Airline,NaN,United Airlines,42,72.0,Yes,10.0,Yes,10.0,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Airline,NaN,Allegiant,38,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Airline,NaN,Southwest,36,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_copy = data.copy()
df_copy['Category'] = df_copy['Score'].rank()
df_copy

,Unnamed: 0,Category,Parent Company,Company,Score,% Dem,Anti-Abortion candidate?,Metric Abortion,Pro-gun candidate?,Metric Gun,Pro-oil candidate?,Metric Oil,Anti-LGBTQ candidate?,Metric LGBTQ,Utilizes prison labor?,Environmental Sourcing,Labor Sourcing,Historical Allegations,% of Discriminatory Cases per year
0,0,495.0,NaN,Frontier,81,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,216.0,NaN,Alaska Airlines,44,54.0,NaN,NaN,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,211.0,NaN,United Airlines,42,72.0,Yes,10.0,Yes,10.0,Yes,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,201.0,NaN,Allegiant,38,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,180.5,NaN,Southwest,36,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,590,22.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,591,22.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,592,22.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,593,22.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,594,22.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
import os

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

import gradio as gr

current_dir = os.path.dirname(os.path.realpath('/content/titanic.csv'))
data = pd.read_csv(os.path.join(current_dir, "/content/titanic.csv"))


def encode_age(df):
    df.Age = df.Age.fillna(-0.5)
    bins = (-1, 0, 5, 12, 18, 25, 35, 60, 120)
    categories = pd.cut(df.Age, bins, labels=False)
    df.Age = categories
    return df


def encode_fare(df):
    df.Fare = df.Fare.fillna(-0.5)
    bins = (-1, 0, 8, 15, 31, 1000)
    categories = pd.cut(df.Fare, bins, labels=False)
    df.Fare = categories
    return df


def encode_df(df):
    df = encode_age(df)
    df = encode_fare(df)
    sex_mapping = {"male": 0, "female": 1}
    df = df.replace({"Sex": sex_mapping})
    embark_mapping = {"S": 1, "C": 2, "Q": 3}
    df = df.replace({"Embarked": embark_mapping})
    df.Embarked = df.Embarked.fillna(0)
    df["Company"] = 0
    df.loc[(df["SibSp"] > 0), "Company"] = 1
    df.loc[(df["Parch"] > 0), "Company"] = 2
    df.loc[(df["SibSp"] > 0) & (df["Parch"] > 0), "Company"] = 3
    df = df[
        [
            "PassengerId",
            "Pclass",
            "Sex",
            "Age",
            "Fare",
            "Embarked",
            "Company",
            "Survived",
        ]
    ]
    return df


train = encode_df(data)

X_all = train.drop(["Survived", "PassengerId"], axis=1)
y_all = train["Survived"]

num_test = 0.20
X_train, X_test, y_train, y_test = train_test_split(
    X_all, y_all, test_size=num_test, random_state=23
)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)


def predict_survival(passenger_class, is_male, age, company, fare, embark_point):
    if passenger_class is None or embark_point is None:
        return None
    df = pd.DataFrame.from_dict(
        {
            "Pclass": [passenger_class + 1],
            "Sex": [0 if is_male else 1],
            "Age": [age],
            "Company": [
                (1 if "Sibling" in company else 0) + (2 if "Child" in company else 0)
            ],
            "Fare": [fare],
            "Embarked": [embark_point + 1],
        }
    )
    df = encode_age(df)
    df = encode_fare(df)
    pred = clf.predict_proba(df)[0]
    return {"Perishes": float(pred[0]), "Survives": float(pred[1])}


demo = gr.Interface(
    predict_survival,
    [
        gr.Dropdown(["first", "second", "third"], type="index"),
        "checkbox",
        gr.Slider(0, 80),
        gr.CheckboxGroup(["Sibling", "Child"], label="Travelling with (select all)"),
        gr.Number(),
        gr.Radio(["S", "C", "Q"], type="index"),
    ],
    "label",
    examples=[
        ["first", True, 30, [], 50, "S"],
        ["second", False, 40, ["Sibling", "Child"], 10, "Q"],
        ["third", True, 30, ["Child"], 20, "S"],
    ],
    interpretation="default",
    live=True,
)

demo.launch()

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://47993.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)

(<gradio.routes.App at 0x7fdf3981cc10>,
 'http://127.0.0.1:7861/',
 'https://47993.gradio.app')

That's all! Go ahead and open that share link in a new tab. Check out our [getting started](https://gradio.app/getting_started.html) page for more complicated demos.

In [23]:

# Working Dataset

import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
#import gradio as gr


#current_dir = os.path.dirname(os.path.realpath( '/content/clean_data.csv'))
#data = pd.read_csv(os.path.join(current_dir, "/content/clean_data.csv"))





def encode_df(df):

    #df = encode_match(df)
    #df = encode_fare(df)

    # Pro Gun
    pro_mapping = {"no": 0, "yes": 1}
    df = df.replace({"Metric Gun": pro_mapping})

    # Pro oil
    pro_mapping = {"no": 0, "yes": 1}
    df = df.replace({"Metric Oil": pro_mapping})

    
    
    # Anti Abortion.   Prolife = meaning they are against abortion.. they recieve 0 (false) match rate, prochoice recieve true matchrate
    anti_mapping ={"yes": 0, "no": 1 }
    df = df.replace({"Metric Abortion": anti_mapping})

    # Anti LGBTQ.  anti meaning 0  for meaning true = 1
    anti_mapping ={"no": 0, "yes": 1 }
    df = df.replace({"Metric LGBTQ": anti_mapping})



    
    #embark_mapping = {"S": 1, "C": 2, "Q": 3}
    #df = df.replace({"Embarked": embark_mapping})
    #df.Embarked = df.Embarked.fillna(0)
    
    df = df[
        [
            "Category",
            "Parent Company",
            "Company",
            "Score",
            "% Dem",
            "Anti-Abortion candidate?", 
            "Metric Abortion" ,
            "Pro-gun candidate?",
            "Metric Gun", 
            "Pro-oil candidate?",
            "Metric Oil", 
            "Anti-LGBTQ candidate?",
            "Metric LGBTQ",
        ]

#category, parent_company, company, donated_Dem,is_NotProchoice, is_Not_Prochoice_metric_, wants_children_to_die, wants_children_to_die_metric, hates_earth,  hates_environment_metric, is_prolly_pedo_for_not_supportingLGBTQ, is_notcool_metric)

    ]
    return df






#clf = RandomForestClassifier()
#clf.fit(X_train, y_train)
#predictions = clf.predict(X_test)



# LABELS:   "Category","Parent Company", "Company", "% Dem","Anti-Abortion candidate?","Pro-gun candidate?", "Pro-oil candidate?","Anti-LGBTQ candidate?",
#. passenger_class, is_male, age, company, fare, embark_point


def predict_survival(category, parent_company, company, score, donated_Dem,is_NotProchoice, is_Not_Prochoice_metric_, wants_children_to_die, wants_children_to_die_metric, hates_earth,  hates_environment_metric, is_prolly_pedo_for_not_supportingLGBTQ, is_notcool_metric):
    if category is None or is_not_coolmetric is None:
        return None
    df = pd.DataFrame.from_dict(
        {   
            
            "Category": [category + 1],
            "Parent Company": [parent_company],
            "Company": [company],
            "Score": [score],
            "% Dem": [donated_Dem],
            "Metric Abortion": [0 if is_Not_Prochoice_metric_ else 1],
            "Metric Gun?": [0 if wants_children_to_die_metric else 1],
            "Metric Oil": [0 if hates_environment_metric else 1],
            "Metric LGBTQ": [0 if is_notcool_metric else 1],
         


            
            #"Embarked": [embark_point + 1],
        }
    )
    #df = encode_age(df)
    #df = encode_fare(df)

    #pred[df] = 1 — wants_children_to_die_metric[‘score’] * 0.1
    pred = clf.predict_proba(df)[0]
    return {"Score": float(pred[0]), "% Dem": float(pred[1])}


demo = gr.Interface(
    predict_survival,
    [
        gr.Dropdown(["Airline", "Auto Insurance", "Auto Part", "Baby", "Bank", "Candy", "Car Rental", "Cellular", "Cleaning Supplies", "Clothing", "Cosmetics", "Drinks", "Electronics", "Food", "Fragrances", "Grocery", "Hair Care", " Home Improvement", "Homeowner's Insurance", "Laundry", "Paper. Products", "Personal Care", " PetCare", "Pharmacy", "Restaurant", "Retail", "Shoes", "Skincare",  "Sportwear","Travel", "Entertainment Industry"], type="index"),
    
        gr.CheckboxGroup(["Pro-gun candidate?", "Pro-oil candidate?","Anti-LGBTQ candidate?","Anti-Abortion candidate?" ], label="Do They Support? "),
        
        gr.Radio(["Demo", "Repub", "Neutral"], type="index"),
    ],
    "label",
    
    interpretation="default",
    live=True,
)

demo.launch()

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://33462.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)

(<gradio.routes.App at 0x7fdf34e680d0>,
 'http://127.0.0.1:7863/',
 'https://33462.gradio.app')

In [24]:
generator1 = gr.Interface.load("huggingface/gpt2")
generator2 = gr.Interface.load("huggingface/EleutherAI/gpt-neo-2.7B")
generator3 = gr.Interface.load("huggingface/EleutherAI/gpt-j-6B")

gr.Parallel(generator1, generator2, generator3).launch()

Fetching model from: https://huggingface.co/gpt2
Fetching model from: https://huggingface.co/EleutherAI/gpt-neo-2.7B
Fetching model from: https://huggingface.co/EleutherAI/gpt-j-6B
Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://41585.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)

(<gradio.routes.App at 0x7fdf32d9dd90>,
 'http://127.0.0.1:7864/',
 'https://41585.gradio.app')

# Image Input


---

In [25]:
import requests
import tensorflow as tf

import gradio as gr

inception_net = tf.keras.applications.MobileNetV2()  # load the model

# Download human-readable labels for ImageNet.
response = requests.get("https://git.io/JJkYN")
labels = response.text.split("\n")

def classify_image(inp):
    inp = inp.reshape((-1, 224, 224, 3))
    inp = tf.keras.applications.mobilenet_v2.preprocess_input(inp)
    prediction = inception_net.predict(inp).flatten()
    return {labels[i]: float(prediction[i]) for i in range(1000)}

image = gr.Image(shape=(224, 224))
label = gr.Label(num_top_classes=3)

demo = gr.Interface(
    fn=classify_image, inputs=image, outputs=label, interpretation="default"
)

demo.launch()

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224.h5
14540800/14536120 [==============================] - 0s 0us/step
14548992/14536120 [==============================] - 0s 0us/step
Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://29907.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces (https://huggingface.co/spaces)

(<gradio.routes.App at 0x7fdec402da10>,
 'http://127.0.0.1:7865/',
 'https://29907.gradio.app')

In [31]:
!pip install -q tensorflow-recommenders
!pip install -q --upgrade tensorflow-datasets

https://colab.research.google.com/github/tensorflow/recommenders/blob/main/docs/examples/quickstart.ipynb#scrollTo=qA00wBE2Ntdm

### Import TFRS

First, install and import TFRS:

In [ ]:
!pip install -q tensorflow-recommenders
!pip install -q --upgrade tensorflow-datasets

     |████████████████████████████████| 85 kB 3.7 MB/s
     |████████████████████████████████| 4.3 MB 8.3 MB/s
     |████████████████████████████████| 98 kB 9.8 MB/s

In [ ]:
from typing import Dict, Text

import numpy as np
import tensorflow as tf

import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs

### Read the data

In [ ]:
# Ratings data.
ratings = tfds.load('movielens/100k-ratings', split="train")
# Features of all the available movies.
movies = tfds.load('movielens/100k-movies', split="train")

# Select the basic features.
ratings = ratings.map(lambda x: {
    "movie_title": x["movie_title"],
    "user_id": x["user_id"]
})
movies = movies.map(lambda x: x["movie_title"])

Downloading and preparing dataset 4.70 MiB (download: 4.70 MiB, generated: 32.41 MiB, total: 37.10 MiB) to ~/tensorflow_datasets/movielens/100k-ratings/0.1.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/100000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/movielens/100k-ratings/0.1.1.incomplete9BXR67/movielens-train.tfrecord*...:   …

Dataset movielens downloaded and prepared to ~/tensorflow_datasets/movielens/100k-ratings/0.1.1. Subsequent calls will reuse this data.
Downloading and preparing dataset 4.70 MiB (download: 4.70 MiB, generated: 150.35 KiB, total: 4.84 MiB) to ~/tensorflow_datasets/movielens/100k-movies/0.1.1...

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/1682 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/movielens/100k-movies/0.1.1.incompleteE6UFJH/movielens-train.tfrecord*...:   0…

Dataset movielens downloaded and prepared to ~/tensorflow_datasets/movielens/100k-movies/0.1.1. Subsequent calls will reuse this data.

Build vocabularies to convert user ids and movie titles into integer indices for embedding layers:

In [ ]:
user_ids_vocabulary = tf.keras.layers.StringLookup(mask_token=None)
user_ids_vocabulary.adapt(ratings.map(lambda x: x["user_id"]))

movie_titles_vocabulary = tf.keras.layers.StringLookup(mask_token=None)
movie_titles_vocabulary.adapt(movies)

### Define a model

We can define a TFRS model by inheriting from `tfrs.Model` and implementing the `compute_loss` method:

In [ ]:
class MovieLensModel(tfrs.Model):
  # We derive from a custom base class to help reduce boilerplate. Under the hood,
  # these are still plain Keras Models.

  def __init__(
      self,
      user_model: tf.keras.Model,
      movie_model: tf.keras.Model,
      task: tfrs.tasks.Retrieval):
    super().__init__()

    # Set up user and movie representations.
    self.user_model = user_model
    self.movie_model = movie_model

    # Set up a retrieval task.
    self.task = task

  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    # Define how the loss is computed.

    user_embeddings = self.user_model(features["user_id"])
    movie_embeddings = self.movie_model(features["movie_title"])

    return self.task(user_embeddings, movie_embeddings)

Define the two models and the retrieval task.

In [ ]:
# Define user and movie models.
user_model = tf.keras.Sequential([
    user_ids_vocabulary,
    tf.keras.layers.Embedding(user_ids_vocabulary.vocab_size(), 64)
])
movie_model = tf.keras.Sequential([
    movie_titles_vocabulary,
    tf.keras.layers.Embedding(movie_titles_vocabulary.vocab_size(), 64)
])

# Define your objectives.
task = tfrs.tasks.Retrieval(metrics=tfrs.metrics.FactorizedTopK(
    movies.batch(128).map(movie_model)
  )
)

WARNING:tensorflow:vocab_size is deprecated, please use vocabulary_size.

WARNING:tensorflow:vocab_size is deprecated, please use vocabulary_size.

WARNING:tensorflow:vocab_size is deprecated, please use vocabulary_size.

WARNING:tensorflow:vocab_size is deprecated, please use vocabulary_size.


### Fit and evaluate it.

Create the model, train it, and generate predictions:

In [ ]:
# Create a retrieval model.
model = MovieLensModel(user_model, movie_model, task)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.5))

# Train for 3 epochs.
model.fit(ratings.batch(4096), epochs=3)

# Use brute-force search to set up retrieval using the trained representations.
index = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
index.index_from_dataset(
    movies.batch(100).map(lambda title: (title, model.movie_model(title))))

# Get some recommendations.
_, titles = index(np.array(["42"]))
print(f"Top 3 recommendations for user 42: {titles[0, :3]}")

Epoch 1/3
25/25 [==============================] - 25s 947ms/step - factorized_top_k/top_1_categorical_accuracy: 7.0000e-05 - factorized_top_k/top_5_categorical_accuracy: 0.0015 - factorized_top_k/top_10_categorical_accuracy: 0.0047 - factorized_top_k/top_50_categorical_accuracy: 0.0456 - factorized_top_k/top_100_categorical_accuracy: 0.1035 - loss: 33083.8682 - regularization_loss: 0.0000e+00 - total_loss: 33083.8682
Epoch 2/3
25/25 [==============================] - 24s 973ms/step - factorized_top_k/top_1_categorical_accuracy: 1.9000e-04 - factorized_top_k/top_5_categorical_accuracy: 0.0055 - factorized_top_k/top_10_categorical_accuracy: 0.0149 - factorized_top_k/top_50_categorical_accuracy: 0.1049 - factorized_top_k/top_100_categorical_accuracy: 0.2108 - loss: 31014.4095 - regularization_loss: 0.0000e+00 - total_loss: 31014.4095
Epoch 3/3
25/25 [==============================] - 24s 963ms/step - factorized_top_k/top_1_categorical_accuracy: 7.6000e-04 - factorized_top_k/top_5_categorical_accuracy: 0.0083 - factorized_top_k/top_10_categorical_accuracy: 0.0224 - factorized_top_k/top_50_categorical_accuracy: 0.1438 - factorized_top_k/top_100_categorical_accuracy: 0.2682 - loss: 30421.7339 - regularization_loss: 0.0000e+00 - total_loss: 30421.7339
Top 3 recommendations for user 42: [b'Rent-a-Kid (1995)'
 b'Land Before Time III: The Time of the Great Giving (1995) (V)'
 b'Steal Big, Steal Little (1995)']